services:
  node-app:
    build: .
    container_name: node-app
    image: node-app-image
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - node-modules:/app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mysql-db
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3307'
    volumes:
      - mysql-db-volume:/var/lib/mysql
volumes:
  node-modules:
  mysql-db-volume:
